# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  default_branch: "main"
  delete_branch_on_merge: true
  private: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  has_issues: true
  has_pages: false
  has_projects: false
  has_wiki: false

labels:
  - name: "automerge"
    color: "#ededed"
    description: ""
    
  - name: "bc break"
    color: "#ff0000"
    description: ""
    
  - name: "bugfix"
    color: "#fc2929"
    description: ""
    
  - name: "dependency"
    color: "#5fb2d8"
    description: ""
    
  - name: "docs"
    color: "#fbca04"
    description: ""
    
  - name: "feature"
    color: "#0e8a16"
    description: ""
    
  - name: "help wanted"
    color: "#159818"
    description: ""
    
  - name: "invalid"
    color: "#e6e6e6"
    description: ""
    
  - name: "pedantic"
    color: "#DDDDDD"
    description: ""
    
  - name: "question"
    color: "#cc317c"
    description: ""

branches:
  - name: "main"
    protection:
      enforce_admins: false
      required_status_checks: null
      required_pull_request_reviews: null
      restrictions: null
