# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  default_branch: "main"
  delete_branch_on_merge: true
  private: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  has_issues: true
  has_pages: false
  has_projects: false
  has_wiki: false

labels:
  - name: "BC Break"
    color: "#ff0000"
    description: ""
    oldname: "bc break"

  - name: "Bug"
    color: "#fc2929"
    description: ""
    oldname: "bugfix"

  - name: "Documentation"
    color: "#fbca04"
    description: ""
    oldname: "docs"

  - name: "Enhancement"
    color: "#5fb2d8"
    description: ""

  - name: "Feature Request"
    color: "#0e8a16"
    description: ""
    oldname: "feature"

  - name: "Help Wanted"
    color: "#159818"
    description: ""
    oldname: "help wanted"

  - name: "Invalid"
    color: "#e6e6e6"
    description: ""

  - name: "Question"
    color: "#cc317c"
    description: ""
    oldname: "question"

  # Technical
  - name: "automerge"
    color: "#ededed"
    description: ""

  # Legacy
  - name: "dependency"
    color: "#5fb2d8"
    description: ""

branches:
  - name: "*.x"
    protection:
      enforce_admins: false
      required_status_checks: null
      required_pull_request_reviews: null
      restrictions: null
